/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void changeStrokeThickness(GCustomSlider source, GEvent event) { //_CODE_:strokeThickness:406718:
  strokeWidth = strokeThickness.getValueF();
} //_CODE_:strokeThickness:406718:

public void blueSlider(GSlider source, GEvent event) { //_CODE_:blueValue:992201:
  blue = blueValue.getValueF();
} //_CODE_:blueValue:992201:

public void redSlider(GSlider source, GEvent event) { //_CODE_:redValue:661982:
  red = redValue.getValueF();
} //_CODE_:redValue:661982:

public void greenSlider(GSlider source, GEvent event) { //_CODE_:greenValue:983477:
  green = greenValue.getValueF();
} //_CODE_:greenValue:983477:

public void slider2d1_change1(GSlider2D source, GEvent event) { //_CODE_:slider2d1:385367:
  println("slider2d1 - GSlider2D >> GEvent." + event + " @ " + millis());
} //_CODE_:slider2d1:385367:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  strokeThickness = new GCustomSlider(this, 10, 30, 190, 45, "grey_blue");
  strokeThickness.setShowValue(true);
  strokeThickness.setLimits(5.0, 0.1, 30.0);
  strokeThickness.setNbrTicks(8);
  strokeThickness.setShowTicks(true);
  strokeThickness.setNumberFormat(G4P.DECIMAL, 1);
  strokeThickness.setOpaque(false);
  strokeThickness.addEventHandler(this, "changeStrokeThickness");
  blueValue = new GSlider(this, 130, 110, 100, 40, 10.0);
  blueValue.setShowValue(true);
  blueValue.setRotation(PI/2, GControlMode.CORNER);
  blueValue.setLimits(0.0, 0.0, 255.0);
  blueValue.setNumberFormat(G4P.DECIMAL, 2);
  blueValue.setOpaque(false);
  blueValue.addEventHandler(this, "blueSlider");
  redValue = new GSlider(this, 50, 110, 100, 40, 10.0);
  redValue.setShowValue(true);
  redValue.setRotation(PI/2, GControlMode.CORNER);
  redValue.setLimits(0.0, 0.0, 255.0);
  redValue.setNumberFormat(G4P.DECIMAL, 2);
  redValue.setLocalColorScheme(GCScheme.RED_SCHEME);
  redValue.setOpaque(false);
  redValue.addEventHandler(this, "redSlider");
  greenValue = new GSlider(this, 90, 110, 100, 40, 10.0);
  greenValue.setShowValue(true);
  greenValue.setRotation(PI/2, GControlMode.CORNER);
  greenValue.setLimits(0.0, 0.0, 255.0);
  greenValue.setNumberFormat(G4P.DECIMAL, 2);
  greenValue.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  greenValue.setOpaque(false);
  greenValue.addEventHandler(this, "greenSlider");
  label1 = new GLabel(this, 10, 10, 190, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Line Width");
  label1.setOpaque(false);
  label2 = new GLabel(this, 10, 90, 190, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Color");
  label2.setOpaque(false);
  slider2d1 = new GSlider2D(this, 222, 121, 109, 94);
  slider2d1.setLimitsX(0.5, 0.0, 1.0);
  slider2d1.setLimitsY(0.5, 0.0, 1.0);
  slider2d1.setNumberFormat(G4P.DECIMAL, 2);
  slider2d1.setOpaque(true);
  slider2d1.addEventHandler(this, "slider2d1_change1");
  togGroup1 = new GToggleGroup();
  togGroup2 = new GToggleGroup();
  togGroup3 = new GToggleGroup();
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider strokeThickness; 
GSlider blueValue; 
GSlider redValue; 
GSlider greenValue; 
GLabel label1; 
GLabel label2; 
GSlider2D slider2d1; 
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GToggleGroup togGroup3; 
